spring:
  application:
    name: auth-api
  datasource:
    url: jdbc:mysql://10.116.64.14:13306/nhn_academy_22?serverTimezone=Asia/Seoul&useSSL=false
    username: nhn_academy_22
    password: "h_8_TkaVj3!4Okzq"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 10.116.64.14
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 22
  session:
    store-type: redis
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083

jwt:
  secret-key: "l7lD/bDeX1yqkdIWdecWa0QvHDLBA0LDAwwFKXYABJkvOSBRCv4Gotox6sATdG7pjoFV563J+CZ9lG54ktkPig=="
  access-token-expiration: 3600000      # 1시간
  refresh-token-expiration: 1209600000  # 2주 - 14일

external:
  account-api:
    url: http://localhost:8081/api/accounts